server:
    port: 11000
debug: true
logging:
    level:
        imall.mapper: DEBUG
spring:
    datasource:
        url: jdbc:mysql://xxx:3306/wechat?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=true&verifyServerCertificate=false&allowMultiQueries=true
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
#       初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
        initialSize: 15
#       最小连接池数量
        minIdle: 0
#       最大连接池数量
        maxActive: 200
#       获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
        maxWait: 60000
#        testWhileIdle的判断依据
        timeBetweenEvictionRunsMillis: 3000
#        配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
#        检测语句
        validationQuery: SELECT 1 FROM DUAL
#        申请连接的时候检测，如果空闲时间大于 timeBetweenEvictionRunsMillis
        testWhileIdle: true
#        申请连接时执行validationQuery检测连接是否有效
        testOnBorrow: true
#        归还连接时执行validationQuery检测连接是否有效
        testOnReturn: false
#        是否缓存preparedStatement，也就是PSCache。 PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql5.5以下的版本中没有PSCache功能，建议关闭掉
        poolPreparedStatements: true
#        指定每个连接上PSCache的大小
        maxPoolPreparedStatementPerConnectionSize: 50
#        连接的自动回收
        removeAbandoned: true
#        回收链接的超时时间
        removeAbandonedTimeout: 300
#        配置扩展插件，监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
        filters: stat, log4j
#        通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
#        合并多个DruidDataSource的监控数据
#        useGlobalDataSourceStat: true
    druid:
        web:
            allow: ''
            deny: ''
            loginPassword: 123456
            loginUsername: admin
            resetEnable: false
